version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run tests
          command: |
            make test
            make cover
      - store_test_results:
          path: ./TestResults
      - run:
          name: Build
          command: |
            PLATFORMS=(darwin linux windows)
            ARCHES=(amd64 arm64)

            for platform in "${PLATFORMS[@]}"; do
              for arch in "${ARCHES[@]}"; do
                ARCH=$arch PLATFORM=$platform make build
              done
            done
      - store_artifacts:
          path: ./out
  release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./out
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./out/

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
