# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    working_directory: ~/repo
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: circleci/golang:1.17
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run tests
          command: |
            make test
            make cover
      - store_test_results:
          path: ./TestResults
      - run:
          name: Build
          command: |
            PLATFORMS=(darwin linux windows)
            ARCHES=(amd64 arm64)

            for platform in "${PLATFORMS[@]}"; do
              for arch in "${ARCHES[@]}"; do
                ARCH=$arch PLATFORM=$platform make build
              done
            done
      - store_artifacts:
          path: ./out
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    requires:
      - build
    filters:
      branches:
        only: master
    steps:
      - attach_workspace:
          at: ./out
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(git rev-parse --short HEAD)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./out/
